### ISSUE TITLE
Edit milestones

### ISSUE THREAD

**Issue by mrzapp** [mrzapp/kanbanhub.js#15]
- [x] write order to cfg
- [x] ajax for creating and deleting milestones
- [x] loading ui (use modal)
- [x] set due date
- [x] set title
- [x] set description
